# ============================================================================
# Apache Airflow ETL Demo Platform - Docker Compose Configuration
# ============================================================================
# Services: Airflow (webserver, scheduler, init), PostgreSQL (Airflow + Warehouse)
# Network: Internal bridge network for service communication
# ============================================================================

version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: docker/airflow/Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # Environment variables from .env file
    WAREHOUSE_HOST: ${WAREHOUSE_HOST:-postgres-warehouse}
    WAREHOUSE_PORT: ${WAREHOUSE_PORT:-5432}
    WAREHOUSE_DB: ${WAREHOUSE_DB:-warehouse}
    WAREHOUSE_USER: ${WAREHOUSE_USER:-warehouse_user}
    WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD:-warehouse_pass}
    SMTP_HOST: ${SMTP_HOST:-}
    SMTP_PORT: ${SMTP_PORT:-587}
    SMTP_USER: ${SMTP_USER:-}
    SMTP_PASSWORD: ${SMTP_PASSWORD:-}
    SMTP_FROM: ${SMTP_FROM:-}
    TEAMS_WEBHOOK_URL: ${TEAMS_WEBHOOK_URL:-}
    TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
    TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./tests:/opt/airflow/tests
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres-airflow:
      condition: service_healthy
    postgres-warehouse:
      condition: service_healthy

services:
  # ============================================================================
  # PostgreSQL - Airflow Metadata Database
  # ============================================================================
  postgres-airflow:
    image: postgres:15-alpine
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow-network

  # ============================================================================
  # PostgreSQL - Mock Data Warehouse
  # ============================================================================
  postgres-warehouse:
    build:
      context: .
      dockerfile: docker/warehouse/Dockerfile
    container_name: airflow-warehouse
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
      POSTGRES_DB: warehouse
    volumes:
      - postgres-warehouse-data:/var/lib/postgresql/data
      - ./src/warehouse/migrations:/migrations
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "warehouse_user", "-d", "warehouse"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - airflow-network

  # ============================================================================
  # Airflow - Database Initialization
  # ============================================================================
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/data
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
        echo "Airflow initialization complete"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
    user: "0:0"
    depends_on:
      <<: *airflow-common-depends-on

  # ============================================================================
  # Airflow - Webserver
  # ============================================================================
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow-network

  # ============================================================================
  # Airflow - Scheduler
  # ============================================================================
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob", "--hostname", "$${HOSTNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow-network

# ============================================================================
# Volumes
# ============================================================================
volumes:
  postgres-airflow-data:
    name: airflow-postgres-data
  postgres-warehouse-data:
    name: airflow-warehouse-data

# ============================================================================
# Networks
# ============================================================================
networks:
  airflow-network:
    driver: bridge
    name: airflow-network
